#!/usr/bin/env bash

# SET PWD TO DIRNAME OF THIS SCRIPT
# this script should always be located next to
# docker-compose.yml & the test_runner package
# directory (containing python env & tests)
current_dir=`dirname "$0"`
cd $current_dir
# go to root directory
cd ..

#
# FUNCTIONS
# 

function stack_up {
    # Uses docker-compose to start dev stack; assumes image is built.
    docker-compose -f $1 up ${@:2}
}

function stack_down {
    # tear down given docker-compose stack
    # only needed if stack was started in detached mode using `-d`
    docker-compose -f $1 down
}

#
# RUN SCRIPT
#

dev_stack="./dev.docker-compose.yml"
test_stack="./tests/integration/test.docker-compose.yml"

if [[ $1 = "test" || $1 = "t" ]]; then
    # only needs the db; test runner creates app for testing as needed
    stack_up $test_stack
else
    stack_up $dev_stack -d
    # Use uvicorn to run FastAPI application & watch for changes
    APP_KEY='insecure_key' uvicorn src:app --reload
    stack_down $dev_stack
fi
